### ISSUE TITLE
use boolean instead of strings on/off in A0301 and A0302

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#10]
Alarms A0301 and A0302 use strings with values "on" and "off" for the "errormode" argument, but a boolean for the "manual" argument.

This seems inconsistent. I suggest using boolean throughout, as this is already used on many other statuses and commands.

**Comment by otterdahl** [comment]
Using "on" and "off" for the "errormode" argument is consistent with the TLC manuals, e.g. while the alarm is active, the detector will logically stay "ON" or "OFF".

Changing to boolean for "errormode", e.g. errormode=true doesn't make much sense. I guess that it would be possible to instead use detector_active=on or something similar, but it is less consistent with other documentation that is typical for TLC's.

**Comment by emiltin** [comment]
ok
