### ISSUE TITLE
Semantic Versioning requires patch version

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#102]
According to https://semver.org/#spec-item-2., "A normal version number MUST take the form X.Y.Z".

We're curently using some versions in the form X.Y, like 3.2. This is causing a bit of confusion when matching versions e.g. in the Ruby gem.

For example, the ITC-3 is reporting it supports 3.2.0, which is currently not matched with 3.2 in the gem. So if the gem is configured to accept only 3.2. they cannot connect.

It's possible to match 3.2 with 3.2.0 by being a bit smarter, but a better solution would be to be more strict about following the X.Y.Z format when versioning our schemas and SXLs.

I suggest we rename the relevant version, of which there is 3:
- core 3.2
- tlc sxl 1.1
- tlc sxl 1.2

**Comment by otterdahl** [comment]
Should be clarify core to require "X.Y.Z"?

**Comment by emiltin** [comment]
> Should be clarify core to require "X.Y.Z"?

I think so, however we probably have to accept that versions released before the that change is released are reported in X.Y format.
