### ISSUE TITLE
Define in alarm/status/command is required or optional

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_schema#11]
Extend the SXL to define if an alarm, status or command is optional or not

The required alarm, status or command is needed to claim that an implementation is RSMP compliant. 

The optional ones can in turn be required by some road authorities. Perhaps a road map when some some of the optional ones will become required

**Comment by emiltin** [comment]
Yes. We might also need to detail if all arguments must be implemented or some are optional

**Comment by otterdahl** [comment]
I think this issue can be closed

**Comment by emiltin** [comment]
was this implemented, or dropped?

**Comment by otterdahl** [comment]
Implemented
