### ISSUE TITLE
Wrong casing in alarm messages? issue/Issue, active/Active

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_schema#14]
There might be wrong casing in alarm messages compared to rsmp_core

E.g.

- **"aSp":"issue"** instead of **"aSp":"Issue"**
- **"aS":"active"** instead of **"aS":"Active"**

See [structure of an alarm message](https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html#structure-for-an-alarm-message) and see [examples](https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/examples.html#alarms)

**Comment by emiltin** [comment]
confirmed

**Comment by emiltin** [comment]
oddly, sS must be one of "suspended", "notSuspended", ie. with first letter downcased
