### ISSUE TITLE
update core to 3.1.5

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#15]
i added support for AggregatedStatusRequest. Are there other changes?

**Comment by otterdahl** [comment]
There is also a possibility with 3.1.5 to request status of an alarm

**Comment by emiltin** [comment]
StatusSubscribe added the 'sOc' attribute:
https://github.com/rsmp-nordic/rsmp_core/commit/c8af9c36825e241aa468cf2706cef97a117781e7

**Comment by emiltin** [comment]
done
