### ISSUE TITLE
allow null for status update 'n' values for core >= 3.1.4

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#20]

**Comment by emiltin** [comment]
is this specified per status message, or is generally allowed for all status messasge, when core <= 3.1.4?

**Comment by emiltin** [comment]
@otterdahl any input on this?

**Comment by otterdahl** [comment]
The 'n' field (short for "name") in status responses and status updates is a unique reference of the value.

I think the specification doesn't clearly define whether 'n' can be set to 'null' or not, but I don't think it makes any sense to set 'n' to 'null'.

From a schema point of view, I don't see any problem allowing 'null' for all fields in status responses or updates.

**Comment by emiltin** [comment]
i don't really recall why i openened this issue. but if it doesn't make sense to set n to null, i think the schema should not allow it?
currently, the schema forbids n=null for all core versions.

**Comment by otterdahl** [comment]
> i don't really recall why i openened this issue. but if it doesn't make sense to set n to null, i think the schema should not allow it? currently, the schema forbids n=null for all core versions.

Right. Since n=null doesn't make sense I think we can keep the current behaviour and not allowing it

**Comment by emiltin** [comment]
alright, closing for now
