### ISSUE TITLE
SXL: timestamp not defined in core

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_schema#26]
In the [sxl.yaml](https://github.com/rsmp-nordic/rsmp_schema/blob/master/schemas/tlc/1.1/sxl.yaml) the type `timestamp` are used in many cases. But `timestamp` [isn't defined in RSMP core](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html?highlight=array#return-values-returnvalue). In most cases [`string` is being used](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#s0025) as type in the SXL where timestamp is used.

However, it is a good idea to add it. And we could move the commonly used description (Format according to W3C...) to the timestamp definition in core and we don't need to define it many times in the SXL.

**Comment by emiltin** [comment]
ok. add a ticket in core?

**Comment by emiltin** [comment]
> ok. add a ticket in core?

added a ticket in core

**Comment by emiltin** [comment]
closing since timestamp was added as a type in core
