### ISSUE TITLE
homemade arrays

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#6]
The validator uses homemade arrays for S0007 and other status:

```ruby
        expect(sS["s"]).to match(/^True|False(,True|False)*$/) if sS["n"] == 'status'
        expect(sS["s"]).to match(/^[1-9](,[1-9])*$/) if sS["n"] == 'intersection'
```

What fields in what statuses uses this type of lists?

**Comment by emiltin** [comment]
Would it be possible use use standard json arrays? [4,3,12,5] instead of "4,3,12,5". Parsing these lists manually is probably error-prone. You have to handle cases like ",1,2,3", "1,2,3," and "1,,2" etc.

**Comment by otterdahl** [comment]
Maybe a better way of doing it would be to use each intersection as an ObjectType.

This is the same issue as https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/58

**Comment by emiltin** [comment]
Closing in favour of the existing issue in the sxl repo rsmp-nordic/rsmp_sxl_traffic_lights#58
