### ISSUE TITLE
Version 1.1.1?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#66]
Recent PRs was merged to master, e.g https://github.com/rsmp-nordic/rsmp_schema/pull/57/files.

Theses changes where done in the `schemas/tlc/1.1/` folder, i.e. we're changing the 1.1 version of the SXL.

Is this correct to amend 1.1? Or should we move these changes to a new version e.g. 1.1.1?

Note also that the corresponding json schema has not been regenerated. Usually, when making changes to the source sxl.yaml file, you run `rake regenerate` to regenerate all the json schema files, and make that part of the PR, so the yaml and the jsons schema are kept in sync.

**Comment by emiltin** [comment]
In this repo, each version of the SXL is kept in a separate folder, rather than just rely on git branches. The reason is that this repo is also a ruby gem that can be used to validate. messages, and you need all the different versions loaded, so you can check messages, regardless of version.

**Comment by emiltin** [comment]
we can name the folder 1.2-draft, and work in that? then when we want to release, we can rename it e.g. 1.1.1 or 1.2?

**Comment by emiltin** [comment]
do we want to make changes to previous version? e.g. fix typos? or do we just leave them, and work on the latest?

**Comment by emiltin** [comment]
> we can name the folder 1.2-draft, and work in that? then when we want to release, we can rename it e.g. 1.1.1 or 1.2?

if we work in a branch (as w should), i guess we don't even need to use draft in the folder name.

**Comment by otterdahl** [comment]
Sure. Lets work in a branch instead

**Comment by emiltin** [comment]
i added a 1.1.1 banch, based off the latest master. it has a new schemas/tlc/1.1.1 folder, created as a copy of schemas/tlc/1.1. PRs should be made against the files in this new 1.1.1 folder
