### ISSUE TITLE
S0006: allow empty emergencystate when status is False

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#69]
the 1.1 spec is not clear about the value of emergencystate when status=False.

Current implementations send an empty string. I suggest we allow this for 1.1 and older. in upcoming version of the sxl, this should be clarified

**Comment by emiltin** [comment]
allowing empty string if status=False can be done in json schema, but not with our sxl yaml source.
instead we can allow emergencystate=0, but that means implementations that send null will fail tests.

**Comment by otterdahl** [comment]
If we allow `null` instead of empty strings, then we should update the core spec as well.

Section 4.4: 
```
Empty values are sent as ""
```

**Comment by emiltin** [comment]
Benefits would be:
- there can be a difference between an empty string and null
- null is a separate type in json and json schema, making it easy to define and validate.

Drawbacks:
- implementations cannot any longer assume that `n` in a status response is always a string. They need to handle nulls.


The simplest we can no now is probably to allow only integers (as string) and define that n=0 means to route active. In upcoming versions of core we can then consider the use of nulls and other native types throughout the spec.

**Comment by emiltin** [comment]
closing, as #70 allows emergencyState=0
